// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkZBUQ2g0Re-OoNIacvNowkG8L2Ehues',
    appId: '1:1080795187806:web:5a59633e059fb3189702cf',
    messagingSenderId: '1080795187806',
    projectId: 'nativox-4f45c',
    authDomain: 'nativox-4f45c.firebaseapp.com',
    storageBucket: 'nativox-4f45c.firebasestorage.app',
    measurementId: 'G-81W8SPYH0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_0D8EMw9zkZjeGK3ALo7B4p6DY1qLrs',
    appId: '1:1080795187806:android:cb738d45511b531f9702cf',
    messagingSenderId: '1080795187806',
    projectId: 'nativox-4f45c',
    storageBucket: 'nativox-4f45c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TsL8TfyoPXLj8BpSKOY0Vq3FsczaJxk',
    appId: '1:1080795187806:ios:e675d59092587ed39702cf',
    messagingSenderId: '1080795187806',
    projectId: 'nativox-4f45c',
    storageBucket: 'nativox-4f45c.firebasestorage.app',
    iosClientId: '1080795187806-crggrcjf60df34kaojo4po26nj56e95r.apps.googleusercontent.com',
    iosBundleId: 'com.example.integrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1TsL8TfyoPXLj8BpSKOY0Vq3FsczaJxk',
    appId: '1:1080795187806:ios:e675d59092587ed39702cf',
    messagingSenderId: '1080795187806',
    projectId: 'nativox-4f45c',
    storageBucket: 'nativox-4f45c.firebasestorage.app',
    iosClientId: '1080795187806-crggrcjf60df34kaojo4po26nj56e95r.apps.googleusercontent.com',
    iosBundleId: 'com.example.integrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkZBUQ2g0Re-OoNIacvNowkG8L2Ehues',
    appId: '1:1080795187806:web:43b37bdfbb31d8d09702cf',
    messagingSenderId: '1080795187806',
    projectId: 'nativox-4f45c',
    authDomain: 'nativox-4f45c.firebaseapp.com',
    storageBucket: 'nativox-4f45c.firebasestorage.app',
    measurementId: 'G-GV5FB71Z9Q',
  );
}
